### ISSUE TITLE
Examples for running the script

### ISSUE THREAD

**Issue by leelasdSI** [meddwl/psearch#1]
Hi, 

I am interested in using your script, I was wondering if there are any examples cases for using the  pmapper. If there is a test case that I could use to run the script that would be great. 

Thanks again for the great work.  This could be really useful for the community.

**Comment by DrrDom** [comment]
Hi,

do you need examples of using pmapper or psearch?
pmapper is a module to calculate pharmacophore hashes, fingerprints and descriptors. This is a separate repository - https://github.com/DrrDom/pmapper. There are several examples in README on that page.
psearch is a module to generate ligand-based models. There are examples how to generate compound library and pharmacophore models in README. Do you have some issues with those scripts? Or what kind of examples would you like to have?

**Comment by leelasdSI** [comment]
Thanks for the quick reply. 
Sorry for the confusion. I need examples for psearch, pmapper has really good examples in README file

**Comment by DrrDom** [comment]
There are just two steps for model generation.
1) generation of databases of actives and inactives from an input SMILES file - `prepare_datatset.py`
2) generation of models from those database files - `psearch.py`
These two steps have examples in README. Do you have issues with them or would you like to have a fully reproducible example? Or do you need more detailed explanation of scripts arguments?

Now we work on a refactored and improved version of psearch which is available in `dev2` branch. It contains a fast screening script which supports multiple input models and some other improvements. However, we did not extensively test the whole package yet. However, we will do this soon to merge in to master. Therefore, if you have some suggestions what kind of examples would be helpful please let us know.

**Comment by leelasd** [comment]
Hi,

I tried running it with psearch-dev2 version and ran into the following error. 

```
psearch -ma compounds/active.smi -mi compounds/inactive.smi -adb active.db -i inactive.db 





models: extract 5 models passed (0.005s)
Traceback (most recent call last):
  File "/Users/leela.dodda/anaconda3/envs/cinf/bin/psearch", line 11, in <module>
    load_entry_point('psearch==0.0.1', 'console_scripts', 'psearch')()
  File "/Users/leela.dodda/anaconda3/envs/cinf/lib/python3.6/site-packages/psearch-0.0.1-py3.6.egg/psearch/psearch.py", line 191, in entry_point
  File "/Users/leela.dodda/anaconda3/envs/cinf/lib/python3.6/site-packages/psearch-0.0.1-py3.6.egg/psearch/psearch.py", line 142, in main
  File "/Users/leela.dodda/anaconda3/envs/cinf/lib/python3.6/site-packages/psearch-0.0.1-py3.6.egg/psearch/psearch.py", line 69, in pharmacophore_validation
NameError: name 'path_pma' is not defined

```

**Comment by DrrDom** [comment]
Thank you for pointing us out. We finished work on a new version and fixed the reported issue. Now this software is a Python package. There are also some changes in command line arguments. Please refer to README or help pages. In the case of question/issue please rise the issue.
