### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by OlgaGKononova** [meddwl/psearch#11]
Hi there,

getting the following error when running `psearch`:

```
python psearch.py -p ../../psearch_test/
models: extract 2 models passed (0.007s)
models: extract 3 models passed (0.007s)
models: extract 1 models passed (0.005s)
models: extract 1 models passed (0.005s)
Traceback (most recent call last):
  File "/psearch/src/psearch.py", line 213, in <module>
    entry_point()
  File "/psearch/src/psearch.py", line 197, in entry_point
    main(mol_act=active_mol,
  File "/psearch/src/psearch.py", line 138, in main
    pharmacophore_validation(mol_act=mol_act,
  File "/psearch/src/psearch.py", line 70, in pharmacophore_validation
    screen_db(db_fname=in_adb, queries=[path_pma], output=screen_act, input_sdf=None,
  File "/psearch/src/scripts/screen_db.py", line 172, in screen_db
    for mol_name, conf_id, out_fname in res:
ValueError: too many values to unpack (expected 3)
```

I had `python prepare_dataset.py -i ../../psearch_test/input_100.smi -n 10` running before that successfully. 

Thank you.

**Comment by OlgaGKononova** [comment]
This only happens for ncpu == 1, for ncpu > 1 works well.

**Comment by DrrDom** [comment]
Hi Olga,

could you tell which version of psearch do you use? Did you install it via pip or from a particular branch of the repository?

Pavel

**Comment by OlgaGKononova** [comment]
I took `master` branch from the repo. Whatever version is there.

**Comment by OlgaGKononova** [comment]
I made this fix in my local version (`screen_db.py`), but I don't have any test to check if it works correctly in all the cases:

```
    if ncpu == 1:
        for mol_name in comp_names:
            for mol_name, conf_id, out_fname in screen(mol_name=mol_name, db_conn=db_fname, models=models, input_sdf=input_sdf, match_first_conf=match_first_conf):
                if not is_sdf_output:
                    #for mol_name, conf_id, out_fname in res:
                    with open(out_fname, 'at') as f:
                        f.write('{}\t{}\n'.format(mol_name, conf_id))
```

If that's okay with you, I can make PR

**Comment by DrrDom** [comment]
One more question:
Which version of pmapper do you use or how did you install it? If you installed it from github master branch when did you do this?

The suggested fix seems strange, because the variable `res` should be unpacked in 3 values and changing the place where we unpack values should not affect the result. I would suggest to use ncpu >1 as a workaround for this time if it works for you.

Currently we are working on a new version and we will try to reproduce this behavior there and will fix it.
As an alternative you may install psearch from the `lib` branch, this is the actual development branch. I worked recently with that version and it was fine.

Thank you for reporting the issue!

**Comment by OlgaGKononova** [comment]
Thank you. I also use the code from master branch for `pmapper`. 

From what I've figured out, `screen(mol_name=mol_name, db_conn=db_fname, models=models, input_sdf=input_sdf, match_first_conf=match_first_conf)` returns an array of tuples, hence `for mol_name, conf_id, out_fname in screen(...)` would iterate over these tuples. 

In case of ncpu > 1, you have another array wrapping an array of tuples (since the multiprocessing), therefore you need to make additional loop with `res`.

**Comment by DrrDom** [comment]
I just checked, the version from `lib` branch works well with `ncpu = 1`. There were many changes and enchantments in that new version, so you may consider to switch to this version. However, I'm not 100% sure that databases generated with the master version will be compatible with the lib version, but you may check.

**Comment by DrrDom** [comment]
If you will use `lib` version please pay attention to this issue https://github.com/meddwl/psearch/issues/12. I just figured this out.

**Comment by OlgaGKononova** [comment]
Okay. Thank you.
