### ISSUE TITLE
possibility of visualising the pharmacophore models

### ISSUE THREAD

**Issue by syedzayyan** [meddwl/psearch#15]
I see the pharmacophore models are .pma files, but can they be visualised using rdkit or ngl?

**Comment by DrrDom** [comment]
You may convert models to xyz-files with `pmapper` and visualize them with pymol using the following plugin - https://github.com/jozefpecha/pymol_plugins

**Comment by syedzayyan** [comment]
Would it be possible to give an example for the pymol command in context to pmapper:

pharm_view pharmacophore_name, mol_name, sphere_scale, sphere_transparency <- I can't get this to work properly in Pymol

I tried with openBabel and nglview but I get this:

<img width="331" alt="Screenshot 2023-04-28 at 12 38 09" src="https://user-images.githubusercontent.com/44922710/235137819-3b7783ca-4cbc-4419-b34d-27bda2684766.png">

And Thank You very much for the help with this so far.

**Comment by syedzayyan** [comment]
Hello! I understand that the issue could have fallen through the email heap. I would really appreciate some help with this. Thank You!

**Comment by DrrDom** [comment]
1. Load a pharmacophore and an aligned ligand or a random one to pymol (the function below will require both a pharmacophore and a ligand objects for visualization)
2. File - Run script - Select this pymol script
3. After that in a pymol console:
`pharm_view XX, YY`
where XX is a name of a pharmacophore object, YY - name of a molecule object

You may edit the script to remove a molecule from the necessary arguments of the function.
