### ISSUE TITLE
Can we save the model in .xyz format

### ISSUE THREAD

**Issue by suneelbvs** [meddwl/psearch#7]
Hi,

Is it possible to save/export the model in xyz format?. 

If we cant save the model in .xyz format; can we visualize the model in any visualizer (pymol, nglview, or any other tools?)

Looking forward for your reply.

Thanks in advance.

Regards,
Suneel

**Comment by DrrDom** [comment]
Hi,
on the first question I answered here https://github.com/DrrDom/pmapper/issues/6
To visualize pharmacophores in xyz format you may use a pymol script - https://github.com/jozefpecha/pymol_plugins

**Comment by suneelbvs** [comment]
Thank you @DrrDom. Really helpful.
